wechat:
  cp:
    corpId: wwffb70143e94111eb
    appConfigs:
      - agentId: 999999
        secret: yeL6mZp5IFIkfQ3wWMGFI8G-L4a6BEF194fnRzhvCy0
        token: 111
        aesKey: 111
      - agentId: 1000002
        secret: 1111
        token: 111
        aesKey: 111
  pay:
    appId:  wxd67baf702dad665c #wxd67baf702dad665c #微信公众号或者小程序等的appid #wx6b73f1161cbfd5f3
    mchId:  1518812711 #微信支付商户号 #1518466961
    mchKey:  nantongjunruanquanjishu888888888 #微信支付商户密钥 #nantonghanhaixinxijishuyouxian88
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    notifyUrl: https://www.ntjunru.com/api/v1/wx/pay/notify/order
  miniapp:
        configs:
            - appid: wxd67baf702dad665c #微信小程序的appid
              secret: a686bebad9b3510abb6c7cdda2f49dfb #微信小程序的Secret
              token: #微信小程序消息服务器配置的token
              aesKey: #微信小程序消息服务器配置的EncodingAESKey
              msgDataFormat: JSON